### ISSUE TITLE
Matlab version

### ISSUE THREAD

**Issue by simangry** [rpng/kalibr_allan#1]
-- MATLAB executable found: /usr/local/bin/matlab
-- MATLAB not found. Set MATLAB_ROOT
-- Will look for MATLAB libraries in 
-- MATLAB not found. If you do have it, set MATLAB_ROOT and reconfigure (missing:  MATLAB_ROOT MATLAB_INCLUDE_DIR MATLAB_LIBRARIES MATLAB_MEXEXT_PATH MATLAB_MEX_EXT) 
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'Eigen3' but neither 'Eigen3_INCLUDE_DIRS' nor
  'Eigen3_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  bagconvert/CMakeLists.txt:20 (catkin_package)

**Comment by goldbattle** [comment]
You might be able to edit the main cmake to set the `MATLAB_ROOT`.
https://github.com/rpng/kalibr_allan/blob/master/bagconvert/cmake/FindMatlab.cmake#L49-L53

For example:
```
set(MATLAB_ROOT "/path/to/your/matlab/folder")
```

I tested this with a default installation of R2016b MATLAB on ubuntu 16.04, where do you have your matlab installed, it looks like it can't find the "mex" libraries needed for a c++ program to interface with making a matlab mat file.
