### ISSUE TITLE
Double sqrt() mathematical error

### ISSUE THREAD

**Issue by tridosh** [rpng/kalibr_allan#10]
The plots should be of the Allan deviation, rather than the variance, so a square root must be taken of the variance for plotting. However, this is done twice in this tool: once just before the end of allan.m, and once in the plot function (loglog()). Thus, the final graph is incorrect, because what is plotted is the square root of the Allan deviation, rather than the Allan deviation.

**Comment by goldbattle** [comment]
Yes, looks like you are correct, thanks for reporting it.
I think I originally thought that it was the variance, not sure why.

Have you used this to get results, are they reasonable?

**Comment by tridosh** [comment]
My results didn't make sense with the double square root, but once I found the problem and took out the extra one, they looked much more reasonable (more closely aligned with the sloped lines, and with the shape of the Allan deviation plots on the spec sheets of the units I was testing).

**Comment by goldbattle** [comment]
I updated the script, and also uploaded some example files that I used back when I first created this project. Let me know if you run into any other issues.
