### ISSUE TITLE
accelerometer_random_walk  is NaN

### ISSUE THREAD

**Issue by icameling** [rpng/kalibr_allan#13]
I use the xsens-MTI-100 dataset download from [here](https://github.com/gaowenliang/imu_utils).The result of accelerometer_random_walk  is NaN.

Here is the terminal output.
```
>> SCRIPT_process_results
=> opening the mat file.
=> plotting accelerometer.
tau = 1.00 | tauid1 = 1190
h_fit1 slope = -0.5000 | y-intercept = -6.7606
h_fit2 slope = 0.5000 | y-intercept = NaN
tau = 2.99 | tauid2 = 1304
=> plotting gyroscope.
tau = 1.00 | tauid1 = 1190
h_fit1 slope = -0.5000 | y-intercept = -8.7292
h_fit2 slope = 0.5000 | y-intercept = -12.9155
tau = 2.99 | tauid2 = 1304
=> final results
accelerometer_noise_density = 0.00115858
accelerometer_random_walk   = NaN
gyroscope_noise_density     = 0.00016179
gyroscope_random_walk       = 0.00000426
```
![results_20190429T144008_accel](https://user-images.githubusercontent.com/12575288/56880177-537b4a80-6a8e-11e9-8b51-f8b5ff323c9b.png)

![results_20190429T144008_gyro](https://user-images.githubusercontent.com/12575288/56880192-62fa9380-6a8e-11e9-9463-325840416abb.png)

I am not familiar with the Allan variance. Could you give me some suggestions?
Thanks a lot!

**Comment by goldbattle** [comment]
See this issue:
https://github.com/rpng/kalibr_allan/issues/12#issuecomment-479292727

You can change how it finds the minimum in the `gen_chart.m` so that it doesn't use the last 100 so it doesn't have that spike included when it tries to fit the line.
