### ISSUE TITLE
matlab error?

### ISSUE THREAD

**Issue by crankler** [rpng/kalibr_allan#15]
When I download the data form google  of imu_mtig700.mat,
and run matlab SCRIPT_process_results.m,
I get a error :

> The variable "results_ax" or class "results_ax.tau1" is not defined.
SCRIPT_process_results (line 30)
[fh1,sigma_a,sigma_ba] = gen_chart(results_ax.tau1,results_ax.sig2,...

How can I do about this error show? Thank you !

**Comment by goldbattle** [comment]
Sorry about the slow reply. That mat file is just the converted bag into matlab format. You would need to first compute the allan variance for that which you can then plot using that script.

If you want to look at the preprocessed file you should download: `results_20170908T182715.mat`
