### ISSUE TITLE
about the results 

### ISSUE THREAD

**Issue by VinchinYang** [rpng/kalibr_allan#18]
We know many sensors have 3 axises accelemeters and 3 axised gyros. I see the results in the figure only have a set of random walk and white noise. Should we consider the other two aixes' noise parameter?

I mean we cannot assume all three axises have the same noise parameter.  Isn't it? :(

**Comment by goldbattle** [comment]
The result reported is the averaged value over each axes' allan deviation
values.
The plot shows this average in purple.
If you want it separate you can checkout the generation function:
https://github.com/rpng/kalibr_allan/blob/master/matlab/functions/gen_chart.m#L4

**Comment by VinchinYang** [comment]
Thanks
