### ISSUE TITLE
Which MATLAB script to run?

### ISSUE THREAD

**Issue by CtfChan** [rpng/kalibr_allan#2]
Hi there, which MATLAB script am I supposed to run after converting the Rosbag to a .mat file?

**Comment by goldbattle** [comment]
The parallel script should be there most up to date. I have not had time to
verify the correctness of the scripts yet.

**Comment by CtfChan** [comment]
Thanks man! I'll give it a try.

**Comment by goldbattle** [comment]
After it process the data, you should be able to run the results script that will graph and build the charts for you. The parallel script just computes the Allen deviation of the given data, and will export to a mat file.

**Comment by CtfChan** [comment]
Hi goldbattle, if I have a 3Hr IMU file how long should it take to run the parallel script? I've been running it for a while and the MATLAB terminal still saids "calculating allan deviation"
