### ISSUE TITLE
Noise density result interpreted from the graph: continuous or discrete

### ISSUE THREAD

**Issue by maximpavliv** [rpng/kalibr_allan#21]
In the [Kalibr repo Wiki](https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model#from-the-allan-standard-deviation-ad) , they talk about continous noise density, and discrete noise density. Using the graph-based method from this repo - does one get the continuous or the discrete noise density? I believe it is the continuous one, but I want to be sure.

**Comment by goldbattle** [comment]
I believe it should give continuous time values.
You might want to check the original paper to be sure:
https://ieeexplore.ieee.org/document/660628
