### ISSUE TITLE
I used kalibr_bagcreater to create my imu.bag

### ISSUE THREAD

**Issue by sheroy666** [rpng/kalibr_allan#4]
I used kalibr_bagcreater to create my imu.bag, and will I mistake the order of gyro data and acce data?

**Comment by goldbattle** [comment]
The bag creater uses the standard IMU format:
https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater#L89-L96

If you want to first create a bag with that creater, then use the bag_converter in this repository that seems like a solid plan.
https://github.com/rpng/kalibr_allan/tree/master/bagconvert

**Comment by sheroy666** [comment]
Thank u so much!
But I have two new questions.
First,if my timestamp is not stable.Even, sometimes it is wrong.But I give the right rate.Will it be OK?
Second,I got two different results.Which one should I use?

> Struct field assignment overwrites a value with class "double". See MATLAB R14SP2 Release Notes, Assigning
Nonstructure Variables As Structures Displays Warning, for details.
tau = 2.99 | tauid2 = 3.010000e+00
tau = 1160.00 | tauid2 = 1161
accelerometer_noise_density = 0.04687453
accelerometer_random_walk   = 0.00172768
accelerometer_random_walk   = 0.00173345
gyroscope_noise_density     = 0.01250441
gyroscope_random_walk   = 0.00172768
gyroscope_random_walk   = 0.00173345

**Comment by goldbattle** [comment]
If the frequency/rate you set is correct, then you should be fine.
Right now there isn't a good way to evaluate the final result, so your best bet would be to test both, or just pick the bigger on.
