### ISSUE TITLE
Meaning of the line in the graph 

### ISSUE THREAD

**Issue by imrasp** [rpng/kalibr_allan#8]
![allan-pixhawk-accelerometer](https://user-images.githubusercontent.com/23768684/42745509-6bfe0aa2-88fd-11e8-9bcf-9a474539745c.png)

I have some trouble about how to interpret these graph. Can some one explain me what is this graph mean. what is cross red and blue line? or suggest me some keyword to search about this.

**Comment by goldbattle** [comment]
So those lines are "fit" to the data of the graph.
I would recommend checking out the kalibr wiki for why we put those lines there:
https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model#from-the-allan-standard-deviation-ad

You can also take a look at this gyroscope standard, key page should be 71 (allan variance, section C):
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=660628&isnumber=14457&tag=1

**Comment by goldbattle** [comment]
![image](https://user-images.githubusercontent.com/2222562/42820375-00b925ae-89a4-11e8-83ad-73a20a0dd408.png)
