### ISSUE TITLE
About the exact format of IMU's outputs for the scripts

### ISSUE THREAD

**Issue by Beniko95J** [rpng/kalibr_allan#9]
Hi,

I have some trouble understanding the exact format of IMU's outputs, which will be the inputs of your functions. The IMU I have outputs instantaneous accelerations along three axes (the unit is m/s^2) and the angle change during a measurement cycle in three axes (the unit is m deg). I have read several materials which told me how to use Allan deviation to analyze IMU noise model, but their IMU seems to output instantaneous angle velocity (the unit is m deg/s) instead of the angle change during a cycle[1]. Would you tell me what is the exact format of IMU's outputs your scripts will accept? Are the outputs instantaneous measurements or the change during a measurement cycle?

PS: I tried to provide the inputs for you scripts with a csv file, but the figure seemed to be a little different from your example. The command window outputs several repeated messages and the figure also have many repeated messages. Would you please give me an idea about this?

Thank you.
![bmi160_gyro](https://user-images.githubusercontent.com/30772597/47960048-e931a200-e036-11e8-8e3f-f7c6ee35e846.png)

[1] http://cache.freescale.com/files/sensors/doc/app_note/AN5087.pdf

**Comment by goldbattle** [comment]
The format expected in the mat files is located here:
https://github.com/rpng/kalibr_allan/blob/master/bagconvert/src/main.cpp#L75-L85

Basically it is: `timestamp(s),x_accel,y_accel,z_accel,x_omega,y_omega,z_omega`
Hope this answers your question.
